#! /bin/bash

./header

./MersadAgent $@ --goalie &
sleep 1

./MersadAgent $@ &
usleep 300000

./MersadAgent $@ &
usleep 300000

./MersadAgent $@ &
usleep 300000

./MersadAgent $@ &
usleep 300000

./MersadAgent $@ &
sleep 1
